# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Deploy Nightly
on:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04
    outputs:
      nightly: ${{ steps.nightly.outputs.nightly }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: nightly
        name: Check if current branch is nightly
        run: (git tag --points-at HEAD | grep -wq "nightly" && echo "nightly=true") || echo "nightly=false" >> $GITHUB_OUTPUT

  create:
    needs: [check]
    if: ${{ needs.check.outputs.nightly == 'false' }}
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Copy static files
        run: |
          mkdir -p dist
          tar -czf dist/layouts.tar.gz layouts

      - name: Create release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete previous nightly if it exists
          gh release delete nightly --yes || true
          git push --delete origin nightly || true
          git tag -d nightly || true

          git tag nightly
          gh release create --prerelease --title "Nightly $(date +'%Y-%m-%d')" --notes-from-tag --target $GITHUB_SHA nightly dist/*

  build:
    needs: [create]
    name: Build on ${{ matrix.arch }}
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: amd64
          - os: ubuntu-24.04-arm
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set version
        run: echo "VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y libmpv-dev
          make build

      - name: Upload dist
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload nightly dist/*
