# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set version
        run: echo "VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - name: Copy static files
        run: |
          mkdir -p dist
          tar -czf dist/layouts.tar.gz layouts

      - name: Create release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --draft --generate-notes --target $GITHUB_SHA $VERSION dist/*

  build:
    needs: [create]
    name: Build on ${{ matrix.arch }}
    permissions: write-all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set version
        run: echo "VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y libmpv-dev
          make build

      - name: Upload dist
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $VERSION dist/*
