# yaml-language-server: https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set version
        run: echo "VERSION=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - name: Build
        run: make workflow-build

      - name: Publish release
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --draft --generate-notes --target $GITHUB_SHA $VERSION dist/*
